version: "3"

services:
  mosquitto:
    container_name: tig-broker
    image: eclipse-mosquitto:2
    volumes:
      - ./mosquitto/:/mosquitto/config/:ro
      - ./logs/:/mosquitto/log/
    ports: 
      - 1883:1883
      - 9001:9001

  influxdb:
    container_name: tig-influxdb
    image: influxdb:2.1.1
    volumes:
      - influxdb-storage:/var/lib/influxdb2:rw
    env_file:
      - .env
    entrypoint: ["./entrypoint.sh"]
    restart: on-failure:10
    ports:
      - ${DOCKER_INFLUXDB_INIT_PORT}:8086

  telegraf:
    container_name: tig-telegraf
    image: telegraf:1.19
    volumes:
      - ${TELEGRAF_CFG_PATH}:/etc/telegraf/telegraf.conf:rw
    env_file:
      - .env
    depends_on:
      - influxdb
      - mosquitto
      - grafana
    restart: on-failure:10

  grafana:
    container_name: tig-grafana
    #image: grafana/grafana-oss:latest
    build: ./grafana_image
    #volumes:
      #- grafana-storage:/var/lib/grafana:rw
      #- ./logs:/var/log/grafana:rw

    env_file:
      - .env
    depends_on:
      - influxdb
    ports:
      - ${GRAFANA_PORT}:3000

  datagen:
    container_name: tig-generator
    build: ./data_generator
    env_file:
      - .env
    depends_on:
      - influxdb
      - mosquitto
    restart: on-failure:10

volumes:
  grafana-storage:
  influxdb-storage:
